# Generated by Django 3.2.6 on 2021-10-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moverspackers', '0003_remove_siteuser_professional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='user',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
